//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecture
    {
        public int id { get; set; }
        public int academic_year { get; set; }
        public string session_title { get; set; }
        public string module_code { get; set; }
        public int week { get; set; }
        public int lecturer { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public int duration { get; set; }
        public string day { get; set; }
        public int session_type { get; set; }
        public int venue { get; set; }
    
        public virtual academic_year academic_year1 { get; set; }
        public virtual lecturer lecturer1 { get; set; }
        public virtual module module { get; set; }
        public virtual session_type session_type1 { get; set; }
        public virtual venue venue1 { get; set; }
    }
}
