//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchedulingDBEntities : DbContext
    {
        public SchedulingDBEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academic_year> academic_year { get; set; }
        public virtual DbSet<access_level> access_level { get; set; }
        public virtual DbSet<lecturer> lecturers { get; set; }
        public virtual DbSet<lecture> lectures { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<session_type> session_type { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<venue> venues { get; set; }
    }
}
